CREATE TABLE [dbo].[TBDISCIPLINA] (
    [Numero] INT           IDENTITY (1, 1) NOT NULL,
    [Nome]   VARCHAR (300) NOT NULL,
    CONSTRAINT [PK_TBDISCIPLINA] PRIMARY KEY CLUSTERED ([Numero] ASC)
);

