CREATE TABLE [dbo].[TBTESTE_TBQUESTAO] (
    [Teste_Numero]   INT NOT NULL,
    [Questao_Numero] INT NOT NULL,
    CONSTRAINT [FK_TBTESTE_TBQUESTAO_TBQUESTAO] FOREIGN KEY ([Questao_Numero]) REFERENCES [dbo].[TBQUESTAO] ([Numero]),
    CONSTRAINT [FK_TBTESTE_TBQUESTAO_TBTESTE] FOREIGN KEY ([Teste_Numero]) REFERENCES [dbo].[TBTESTE] ([Numero])
);

